[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "22" }

[[redirects]]
  from = "/php-2023"
  to = "https://docs.google.com/presentation/d/1iQiA4POpOdirGfnbXEen_ng646EQmIYN6pk3e4_ynH0/edit?usp=sharing"
  status = 301

[[redirects]]
  from = "htmx-fixes-html"
  to = "https://docs.google.com/presentation/d/1s2VARds0z0ukoP4NSZZe6WP7cWc_z20Ybgcbq8xvABg/edit?usp=sharing"
  status = 301

[[redirects]]
  from = "/game-jamming"
  to = "https://docs.google.com/presentation/d/1fEtnSuuW_TaMaG-tpRzAKS-uvvaOqIlr9NKkf-W5NfM/edit?usp=sharing"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Opting your Website out of Google's FLoC Network
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"
