jobs:
  test:
    docker:
      - image: circleci/node:latest-browsers
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-deps-{{ checksum "package-lock.json" }}
          # Fallback to using the latest cache if no exact match is found
          - v1-deps-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package-lock.json" }}

      # TODO: Change this test to run against netlify deploys on each branch
      # Current runs against the live site
      - run: npm run test

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test