name: ci

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup node env 🏗
        uses: actions/setup-node@v4.3.0
        with:
          node-version: 22.14

      - name: Cache node_modules 📦
        uses: actions/cache@v4.2.3
        with:
          path: ~/.npm
          key: package-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            package-

      - name: Install dependencies 👨🏻‍💻
        run: npm ci --prefer-offline --no-audit

      - name: Run linter 👀
        run: npm run lint

      - name: Generate site 🚀
        run: npm run build
